const colorNames = {
  aliceblue: 'Alice Blue',
  antiquewhite: 'Antique White',
  aqua: 'Aqua',
  aquamarine: 'Aquamarine',
  azure: 'Azure',
  beige: 'Beige',
  bisque: 'Bisque',
  black: 'Black',
  blanchedalmond: 'Blanched Almond',
  blue: 'Blue',
  blueviolet: 'Blue Violet',
  brown: 'Brown',
  burlywood: 'Burly Wood',
  cadetblue: 'Cadet Blue',
  chartreuse: 'Chartreuse',
  chocolate: 'Chocolate',
  coral: 'Coral',
  cornflowerblue: 'Cornflower Blue',
  cornsilk: 'Cornsilk',
  crimson: 'Crimson',
  cyan: 'Cyan',
  darkblue: 'Dark Blue',
  darkcyan: 'Dark Cyan',
  darkgoldenrod: 'Dark Golden Rod',
  darkgray: 'Dark Gray',
  darkgrey: 'Dark Grey',
  darkgreen: 'Dark Green',
  darkkhaki: 'Dark Khaki',
  darkmagenta: 'Dark Magenta',
  darkolivegreen: 'Dark Olive Green',
  darkorange: 'Dark Orange',
  darkorchid: 'Dark Orchid',
  darkred: 'Dark Red',
  darksalmon: 'Dark Salmon',
  darkseagreen: 'Dark Sea Green',
  darkslateblue: 'Dark Slate Blue',
  darkslategray: 'Dark Slate Gray',
  darkslategrey: 'Dark Slate Grey',
  darkturquoise: 'Dark Turquoise',
  darkviolet: 'Dark Violet',
  deeppink: 'Deep Pink',
  deepskyblue: 'Deep Sky Blue',
  dimgray: 'Dim Gray',
  dimgrey: 'Dim Grey',
  dodgerblue: 'Dodger Blue',
  firebrick: 'Fire Brick',
  floralwhite: 'Floral White',
  forestgreen: 'Forest Green',
  fuchsia: 'Fuchsia',
  gainsboro: 'Gainsboro',
  ghostwhite: 'Ghost White',
  gold: 'Gold',
  goldenrod: 'Golden Rod',
  gray: 'Gray',
  grey: 'Grey',
  green: 'Green',
  greenyellow: 'Green Yellow',
  honeydew: 'Honey Dew',
  hotpink: 'Hot Pink',
  indianred: 'Indian Red',
  indigo: 'Indigo',
  ivory: 'Ivory',
  khaki: 'Khaki',
  lavender: 'Lavender',
  lavenderblush: 'Lavender Blush',
  lawngreen: 'Lawn Green',
  lemonchiffon: 'Lemon Chiffon',
  lightblue: 'Light Blue',
  lightcoral: 'Light Coral',
  lightcyan: 'Light Cyan',
  lightgoldenrodyellow: 'Light Golden Rod Yellow',
  lightgray: 'Light Gray',
  lightgrey: 'Light Grey',
  lightgreen: 'Light Green',
  lightpink: 'Light Pink',
  lightsalmon: 'Light Salmon',
  lightseagreen: 'Light Sea Green',
  lightskyblue: 'Light Sky Blue',
  lightslategray: 'Light Slate Gray',
  lightslategrey: 'Light Slate Grey',
  lightsteelblue: 'Light Steel Blue',
  lightyellow: 'Light Yellow',
  lime: 'Lime',
  limegreen: 'Lime Green',
  linen: 'Linen',
  magenta: 'Magenta',
  maroon: 'Maroon',
  mediumaquamarine: 'Medium Aqua Marine',
  mediumblue: 'Medium Blue',
  mediumorchid: 'Medium Orchid',
  mediumpurple: 'Medium Purple',
  mediumseagreen: 'Medium Sea Green',
  mediumslateblue: 'Medium Slate Blue',
  mediumspringgreen: 'Medium Spring Green',
  mediumturquoise: 'Medium Turquoise',
  mediumvioletred: 'Medium Violet Red',
  midnightblue: 'Midnight Blue',
  mintcream: 'Mint Cream',
  mistyrose: 'Misty Rose',
  moccasin: 'Moccasin',
  navajowhite: 'Navajo White',
  navy: 'Navy',
  oldlace: 'Old Lace',
  olive: 'Olive',
  olivedrab: 'Olive Drab',
  orange: 'Orange',
  orangered: 'Orange Red',
  orchid: 'Orchid',
  palegoldenrod: 'Pale Golden Rod',
  palegreen: 'Pale Green',
  paleturquoise: 'Pale Turquoise',
  palevioletred: 'Pale Violet Red',
  papayawhip: 'Papaya Whip',
  peachpuff: 'Peach Puff',
  peru: 'Peru',
  pink: 'Pink',
  plum: 'Plum',
  powderblue: 'Powder Blue',
  purple: 'Purple',
  rebeccapurple: 'Rebecca Purple',
  red: 'Red',
  rosybrown: 'Rosy Brown',
  royalblue: 'Royal Blue',
  saddlebrown: 'Saddle Brown',
  salmon: 'Salmon',
  sandybrown: 'Sandy Brown',
  seagreen: 'Sea Green',
  seashell: 'Sea Shell',
  sienna: 'Sienna',
  silver: 'Silver',
  skyblue: 'Sky Blue',
  slateblue: 'Slate Blue',
  slategray: 'Slate Gray',
  slategrey: 'Slate Grey',
  snow: 'Snow',
  springgreen: 'Spring Green',
  steelblue: 'Steel Blue',
  tan: 'Tan',
  teal: 'Teal',
  thistle: 'Thistle',
  tomato: 'Tomato',
  turquoise: 'Turquoise',
  violet: 'Violet',
  wheat: 'Wheat',
  white: 'White',
  whitesmoke: 'White Smoke',
  yellow: 'Yellow',
  yellowgreen: 'Yellow Green',
}

export default colorNames
